// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbMMcNY5OsLM1xuawgMnwtk9PJn6zaBPA',
    appId: '1:488223158861:web:c83287cb4d0d41f60ee204',
    messagingSenderId: '488223158861',
    projectId: 'servexa-fe67e',
    authDomain: 'servexa-fe67e.firebaseapp.com',
    storageBucket: 'servexa-fe67e.firebasestorage.app',
    measurementId: 'G-ZVQQLF9QBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS7rW3ThFpDPZbayepyUf0fqVaybAq0S8',
    appId: '1:488223158861:android:20cd02a2749154380ee204',
    messagingSenderId: '488223158861',
    projectId: 'servexa-fe67e',
    storageBucket: 'servexa-fe67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi1UWqsZ2qAS2HJGji2Rw5Ds7KheQY_do',
    appId: '1:488223158861:ios:677cac5611c85b310ee204',
    messagingSenderId: '488223158861',
    projectId: 'servexa-fe67e',
    storageBucket: 'servexa-fe67e.firebasestorage.app',
    iosBundleId: 'com.example.servexaProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi1UWqsZ2qAS2HJGji2Rw5Ds7KheQY_do',
    appId: '1:488223158861:ios:677cac5611c85b310ee204',
    messagingSenderId: '488223158861',
    projectId: 'servexa-fe67e',
    storageBucket: 'servexa-fe67e.firebasestorage.app',
    iosBundleId: 'com.example.servexaProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcGcaQDHGjxgPwQ0WLFQ0_YtWvv7dvvaQ',
    appId: '1:488223158861:web:b38fc9b068db343c0ee204',
    messagingSenderId: '488223158861',
    projectId: 'servexa-fe67e',
    authDomain: 'servexa-fe67e.firebaseapp.com',
    storageBucket: 'servexa-fe67e.firebasestorage.app',
    measurementId: 'G-17GTPYY7EX',
  );
}
